### ISSUE TITLE
npm install 安装报错

### ISSUE THREAD

**Issue by LCYBFF** [houdunwang/vue#5]
错误提示：
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:@kangc/v-md-editor/lib/style/base-editor.css

npm版本：v18.15.0（原来v16.14.0也出现以上错误）

报错日志：
0 verbose cli D:\NPM\node.exe D:\NPM\node_modules\npm\bin\npm-cli.js
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:D:\NPM\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:D:\phpstudy_pro\WWW\vue\houdunren-vue\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\Admin\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\Admin\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 9ms
17 timing npm:load:configload Completed in 9ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install
21 verbose argv "install"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 3ms
24 timing npm:load:display Completed in 4ms
25 verbose logfile logs-max:10 dir:C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-03-13T13_07_06_338Z-
26 verbose logfile C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-03-13T13_07_06_338Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 24ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 2 files
33 timing arborist:ctor Completed in 0ms
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 13ms
36 timing idealTree:userRequests Completed in 1ms
37 silly idealTree buildDeps
38 silly fetch manifest @element-plus/icons-vue@^2.0.10
39 http fetch GET 200 https://registry.npmmirror.com/@element-plus%2ficons-vue 17ms (cache hit)
40 silly fetch manifest vue@^3.2.41
41 http fetch GET 200 https://registry.npmmirror.com/vue 7ms (cache hit)
42 silly fetch manifest @icon-park/vue-next@^1.4.2
43 http fetch GET 200 https://registry.npmmirror.com/@icon-park%2fvue-next 10ms (cache hit)
44 silly fetch manifest @kangc/v-md-editor@^2.3.15
45 http fetch GET 200 https://registry.npmmirror.com/@kangc%2fv-md-editor 7ms (cache hit)
46 silly fetch manifest @vue/compiler-sfc@^3.0.0
47 http fetch GET 200 https://registry.npmmirror.com/@vue%2fcompiler-sfc 6ms (cache hit)
48 silly fetch manifest @types/gsap@^3.0.0
49 http fetch GET 200 https://registry.npmmirror.com/@types%2fgsap 5ms (cache hit)
50 silly fetch manifest @types/lodash@^4.14.188
51 http fetch GET 200 https://registry.npmmirror.com/@types%2flodash 4ms (cache hit)
52 silly fetch manifest @types/mockjs@^1.0.7
53 http fetch GET 200 https://registry.npmmirror.com/@types%2fmockjs 6ms (cache hit)
54 silly fetch manifest @vee-validate/i18n@^4.7.2
55 http fetch GET 200 https://registry.npmmirror.com/@vee-validate%2fi18n 4ms (cache hit)
56 silly fetch manifest @vee-validate/rules@^4.7.2
57 http fetch GET 200 https://registry.npmmirror.com/@vee-validate%2frules 6ms (cache hit)
58 silly fetch manifest @vitejs/plugin-vue-jsx@^2.1.1
59 http fetch GET 200 https://registry.npmmirror.com/@vitejs%2fplugin-vue-jsx 5ms (cache hit)
60 silly fetch manifest vite@^3.2.3
61 http fetch GET 200 https://registry.npmmirror.com/vite 6ms (cache hit)
62 silly fetch manifest @types/node@>= 14
63 http fetch GET 200 https://registry.npmmirror.com/@types%2fnode 7ms (cache hit)
64 silly fetch manifest less@*
65 http fetch GET 200 https://registry.npmmirror.com/less 6ms (cache hit)
66 silly fetch manifest sass@^1.56.0
67 http fetch GET 200 https://registry.npmmirror.com/sass 4ms (cache hit)
68 silly fetch manifest stylus@*
69 http fetch GET 200 https://registry.npmmirror.com/stylus 5ms (cache hit)
70 silly fetch manifest sugarss@*
71 http fetch GET 200 https://registry.npmmirror.com/sugarss 6ms (cache hit)
72 silly fetch manifest postcss@^8.4.18
73 http fetch GET 200 https://registry.npmmirror.com/postcss 4ms (cache hit)
74 silly fetch manifest terser@^5.4.0
75 http fetch GET 200 https://registry.npmmirror.com/terser 5ms (cache hit)
76 silly fetch manifest @vueuse/core@^9.4.0
77 http fetch GET 200 https://registry.npmmirror.com/@vueuse%2fcore 4ms (cache hit)
78 silly fetch manifest @wangeditor/editor@^5.1.22
79 http fetch GET 200 https://registry.npmmirror.com/@wangeditor%2feditor 4ms (cache hit)
80 silly fetch manifest @wangeditor/editor-for-vue@^5.1.12
81 http fetch GET 200 https://registry.npmmirror.com/@wangeditor%2feditor-for-vue 5ms (cache hit)
82 silly fetch manifest animate.css@^4.1.1
83 http fetch GET 200 https://registry.npmmirror.com/animate.css 5ms (cache hit)
84 silly fetch manifest axios@^1.1.3
85 http fetch GET 200 https://registry.npmmirror.com/axios 4ms (cache hit)
86 timing idealTree Completed in 246ms
87 timing command:install Completed in 252ms
88 verbose stack Error: Unsupported URL Type "link:": link:@kangc/v-md-editor/lib/style/base-editor.css
88 verbose stack     at unsupportedURLType (D:\NPM\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:327:15)
88 verbose stack     at fromURL (D:\NPM\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:387:13)
88 verbose stack     at Function.resolve (D:\NPM\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:83:12)
88 verbose stack     at [nodeFromEdge] (D:\NPM\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1058:22)
88 verbose stack     at [buildDepStep] (D:\NPM\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:929:36)
88 verbose stack     at async Arborist.buildIdealTree (D:\NPM\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:207:7)
88 verbose stack     at async Promise.all (index 1)
88 verbose stack     at async Arborist.reify (D:\NPM\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
88 verbose stack     at async Install.exec (D:\NPM\node_modules\npm\lib\commands\install.js:146:5)
88 verbose stack     at async module.exports (D:\NPM\node_modules\npm\lib\cli.js:134:5)
89 verbose cwd D:\phpstudy_pro\WWW\vue\houdunren-vue
90 verbose Windows_NT 10.0.19044
91 verbose node v18.15.0
92 verbose npm  v9.5.0
93 error code EUNSUPPORTEDPROTOCOL
94 error Unsupported URL Type "link:": link:@kangc/v-md-editor/lib/style/base-editor.css
95 verbose exit 1
96 timing npm Completed in 299ms
97 verbose unfinished npm timer reify 1678712826382
98 verbose unfinished npm timer reify:loadTrees 1678712826384
99 verbose unfinished npm timer idealTree:buildDeps 1678712826399
100 verbose unfinished npm timer idealTree:#root 1678712826399
101 verbose code 1
102 error A complete log of this run can be found in:
102 error     C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-03-13T13_07_06_338Z-debug-0.log

**Comment by houdunwang** [comment]
问题已经修复了，重新下载就可以了
